### PR TITLE
Added "The OOP in PHP" to Slides

### PR DESCRIPTION
**Pull request by elazar**

### CODE REVIEW

**Comment by marcel-burkhard** [comment]
Looks good, although I would advise you to put the "more to come" part back in below the link you added. Until the list reaches a certain size.

**Comment by elazar** [comment]
@burki94 Done.

**Comment by marcel-burkhard** [comment]
+1 for this PR

**Comment by elazar** [comment]
@marcelgsantos Any chance of this being merged, or should I close it?

**Comment by marcelgsantos** [comment]
Thanks for contributing and sorry for the delay. ;)

**Pull request merged**
