### PR TITLE
@jmikola works on the less-prestigious Doctrine ODM

### PR DESCRIPTION
**Pull request by jmikola**

### CODE REVIEW

**Comment by jwage** [comment]
thumbs_walter

**Comment by jmikola** [comment]
@jcarouth [helpfully reminded me](https://twitter.com/jcarouth/status/560969526935052288) that I also have some affiliation with [WurstCon](http://wurstcon.com), so I amended the commit. :+1:

**Comment by jcarouth** [comment]
approved

**Comment by lsmith77** [comment]
hmm this is strange. it seems this repository is about PHP stuff but I do not have commit rights. something more serious seems to be broken.

**Comment by jcarouth** [comment]
@lsmith77 I think you should demand an immediate refund.

**Comment by lsmith77** [comment]
indeed!

**Comment by marcelgsantos** [comment]
Thanks for contributing @jmikola and @jcarouth. Sorry for the delay. ;)

**Comment by marcelgsantos** [comment]
Hey @lsmith77, what kind of problem you are having?

**Comment by lsmith77** [comment]
just joking. all is well :)

**Pull request merged**
